import esbuild from "esbuild";
import cssModulesPlugin from "esbuild-css-modules-plugin";
import process from "process";
import builtins from "builtin-modules";
import { execSync } from "child_process";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const rootDir = join(dirname(fileURLToPath(import.meta.url)));

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/core/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: prod ? "info" : "verbose",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	splitting: false,
	chunkNames: 'chunks/[name]-[hash]',
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"'
	},
	metafile: true,
	drop: prod ? ['console', 'debugger'] : [],
	keepNames: true,
	legalComments: 'none',
	mainFields: ['module', 'main'],
	resolveExtensions: ['.tsx', '.ts', '.jsx', '.js', '.json'],
	// PNG/JPG are NOT inlined — ship under assets/ and load via getPluginAssetUrl()
	loader: {
		'.png': 'file',
		'.jpg': 'file',
		'.jpeg': 'file',
		'.gif': 'file',
		'.svg': 'file',
	},
	plugins: [
		cssModulesPlugin({
			inject: true,
			localsConvention: 'camelCase',
			generateScopedName: prod ? '[hash:base64:5]' : '[name]__[local]'
		}),
		{
			name: 'performance-optimizer',
			setup(build) {
				if (!prod) {
					build.onLoad({ filter: /\.(ts|tsx)$/ }, (args) => {
						return {
							contents: `// Performance marker: ${args.path}\n${args.contents}`,
							loader: args.path.endsWith('.tsx') ? 'tsx' : 'ts'
						};
					});
				}
			}
		}
	],
});

if (prod) {
	await context.rebuild();
	execSync('node scripts/copy-plugin-assets.mjs', { cwd: rootDir, stdio: 'inherit' });
	execSync('node scripts/verify-plugin-build.mjs', { cwd: rootDir, stdio: 'inherit' });
	console.log("✅ Production build completed successfully!");
	process.exit(0);
} else {
	await context.watch();
}
