import esbuild from "esbuild";
import cssModulesPlugin from "esbuild-css-modules-plugin";
import process from "process";
import builtins from "builtin-modules";
import { readFile } from "fs/promises";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// File loader plugin for handling PNG files
const fileLoaderPlugin = {
	name: 'file-loader',
	setup(build) {
		build.onLoad({ filter: /\.(png|jpg|jpeg|gif|svg)$/ }, async (args) => {
			try {
				const contents = await readFile(args.path);
				const base64 = contents.toString('base64');
				const ext = args.path.split('.').pop();
				const mimeType = {
					png: 'image/png',
					jpg: 'image/jpeg',
					jpeg: 'image/jpeg',
					gif: 'image/gif',
					svg: 'image/svg+xml'
				}[ext];

				return {
					contents: `export default "data:${mimeType};base64,${base64}";`,
					loader: 'js'
				};
			} catch (error) {
				console.error(`Error loading file ${args.path}:`, error);
				return {
					contents: `export default "";`,
					loader: 'js'
				};
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/core/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: prod ? "info" : "verbose",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod, // Re-enable minification for desktop builds
	splitting: false, // Obsidian doesn't support code splitting
	chunkNames: 'chunks/[name]-[hash]',
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"'
	},
	metafile: true, // Enable metafile for CSS modules plugin
	// Enhanced optimization settings
	drop: prod ? ['console', 'debugger'] : [], // Remove console logs in production
	keepNames: true, // Always keep function names to avoid mobile constructor issues
	legalComments: 'none', // Remove legal comments to reduce bundle size
	// Performance optimizations
	mainFields: ['module', 'main'], // Prefer ES modules when available
	resolveExtensions: ['.tsx', '.ts', '.jsx', '.js', '.json'], // Optimize module resolution
	plugins: [
		cssModulesPlugin({
			inject: true,
			localsConvention: 'camelCase', // Convert kebab-case to camelCase
			generateScopedName: prod ? '[hash:base64:5]' : '[name]__[local]'
		}),
		fileLoaderPlugin,
		// Performance optimization plugin (simplified)
		{
			name: 'performance-optimizer',
			setup(build) {
				// Add performance markers for development only
				if (!prod) {
					build.onLoad({ filter: /\.(ts|tsx)$/ }, (args) => {
						return {
							contents: `// Performance marker: ${args.path}\n${args.contents}`,
							loader: args.path.endsWith('.tsx') ? 'tsx' : 'ts'
						};
					});
				}
			}
		}
	],
});

if (prod) {
	await context.rebuild();
	console.log("✅ Production build completed successfully!");
	process.exit(0);
} else {
	await context.watch();
}
