import esbuild from 'esbuild';
import { copyFileSync, mkdirSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const here = path.dirname(fileURLToPath(import.meta.url));
const mobileRoot = path.join(here, '..', 'mobile');
const outDir = path.join(here, '..', '..', 'Gamification-Mobile');
const prod = process.argv.includes('production');

mkdirSync(outDir, { recursive: true });

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Gamification Mobile companion plugin
*/
`;

await esbuild.build({
	banner: { js: banner },
	entryPoints: [path.join(mobileRoot, 'src', 'main.ts')],
	bundle: true,
	format: 'cjs',
	platform: 'browser',
	target: 'es2018',
	outfile: path.join(outDir, 'main.js'),
	external: ['obsidian', 'electron'],
	minify: prod,
	sourcemap: !prod,
	treeShaking: true,
	logLevel: 'info',
});

copyFileSync(path.join(mobileRoot, 'manifest.json'), path.join(outDir, 'manifest.json'));
copyFileSync(path.join(mobileRoot, 'styles.css'), path.join(outDir, 'styles.css'));

console.log(`✅ Mobile plugin built to ${outDir}`);
